# Generated by Django 5.2.6 on 2025-09-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_share_id', models.PositiveIntegerField(unique=True)),
                ('scrip', models.CharField(max_length=20)),
                ('company_name', models.CharField(max_length=255)),
                ('share_type_name', models.CharField(max_length=50)),
                ('share_group_name', models.CharField(max_length=100)),
                ('sub_group', models.CharField(max_length=100)),
                ('status_name', models.CharField(max_length=50)),
                ('issue_open_date', models.DateTimeField()),
                ('issue_close_date', models.DateTimeField()),
            ],
        ),
    ]
