# Generated by Django 5.2.6 on 2025-09-05 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDetials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dp_id', models.CharField(max_length=20, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('crn_number', models.CharField(max_length=20, unique=True)),
                ('pin', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ClientDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('accountBrachnId', models.CharField(max_length=10)),
                ('account_number', models.CharField(max_length=20, unique=True)),
                ('customer_id', models.CharField(max_length=10, unique=True)),
                ('account_type_id', models.CharField(max_length=5)),
                ('bank_id', models.CharField(max_length=5)),
                ('client_boid', models.CharField(max_length=20, unique=True)),
                ('client_demat', models.CharField(max_length=30, unique=True)),
            ],
        ),
    ]
