# Generated by Django 5.2.6 on 2025-09-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DpIdReverse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dp_id', models.CharField(max_length=20, unique=True)),
                ('clientId', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
