# Generated by Django 5.2.6 on 2025-09-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_dpidreverse'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdetials',
            name='clientId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
