# Generated by Django 5.2.6 on 2025-09-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_accountdetials_clientid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdetials',
            name='dp_id',
            field=models.CharField(max_length=20),
        ),
    ]
