# Generated by Django 5.2.6 on 2025-09-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_accountdetials_dp_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=10, unique=True)),
                ('account_number', models.CharField(max_length=20, unique=True)),
                ('account_type_id', models.CharField(max_length=5)),
                ('bank_id', models.CharField(max_length=5)),
                ('account_branch_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='ClientDetails',
        ),
    ]
